version: "3.9"
services:
  web:
    image: tracking-inventory
    container_name: tracking-inventory
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - APP_USERNAME=${POSTGRES_USERNAME}
      - APP_PASSWORD=${POSTGRES_PASSWORD}
      - APP_DBNAME=${POSTGRES_DBNAME}
    volumes:
      - ./:/app

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge

volumes:
  db_data: {}
